---
- name: install apache php
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
    state: present
  become: yes

- name: apache run
  service:
    name: apache2
    state: started
    enabled: yes
  become: yes

- name: get site
  copy:
    src: website/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0755'
  become: yes

- name: replace default index
  file:
    path: /var/www/html/index.html
    state: absent
  become: yes
